version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/react-docker:delegated
      - /node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  bokf-db:
    image: docker.io/postgres
    environment:
      - POSTGRES_DB=bokforing
      - POSTGRES_USER=linus
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/bokforing_db:/var/lib/postgresql/data
      - ./:/react-docker:delegated
      - /node_modules
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "bokforing",
          "-U",
          "linus"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - linus_network

networks:
  linus_network:
